### ISSUE TITLE
Issues on Laravel 8

### ISSUE THREAD

**Issue by devmaufh** [stefanzweifel/laravel-stats#186] opened 2020-10-12 20:59 UTC
When I try to run 
```
PHP artisan stats
```
I'm getting the next message:

LogicException 
You must call one of in() or append() methods before iterating over a Finder.

**Comment by stefanzweifel** [comment] 2020-10-13 06:13
Is the LogicException really thrown from the `laravel-stats`-package? Or maybe from a different part of the application?

The Finder should be built correctly in the stats package. Otherwise our testsuite should fail when testing against Laravel 8 🤔 
https://github.com/stefanzweifel/laravel-stats/blob/51826b3a0cc274e23c475ab40f5b6b8eae23cd55/src/ClassesFinder.php#L46-L48

Could you share your exact Laravel and PHP Version and your `config/stats.php` file?

Is `symfony/finder` a direct dependency in your Laravel application? Maybe we run into a problem here.

**Comment by kyleboehlen** [comment] 2020-10-27 17:20
I am also having the same issue with Laravel 8.

`symfony/finder` is not a direct dependency in my Laravel application, and it's not coming from a different part of my application.

Here is the full error:
```
LogicException

  You must call one of in() or append() methods before iterating over a Finder.

  at vendor/symfony/finder/Finder.php:610
    606|      */
    607|     public function getIterator()
    608|     {
    609|         if (0 === \count($this->dirs) && 0 === \count($this->iterators)) {
  > 610|             throw new \LogicException('You must call one of in() or append() methods before iterating over a Finder.');
    611|         }
    612|
    613|         if (1 === \count($this->dirs) && 0 === \count($this->iterators)) {
    614|             return $this->searchInDirectory($this->dirs[0]);

  1   [internal]:0
      Symfony\Component\Finder\Finder::getIterator()

      +20 vendor frames
  22  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

Environment: Ubuntu 20.04.1 LTS, PHP 7.4.3, and I did not publish the vendor files for the package so no changes to `config/stats.php` made.

**Comment by kyleboehlen** [comment] 2020-10-27 18:31
I resolved this issue by publishing the vendor config and caching the config.

For anybody else that comes across this issue: 
`php artisan vendor:publish --provider="Wnx\LaravelStats\StatsServiceProvider"`
`config:cache`

**Comment by stefanzweifel** [comment] 2020-10-27 18:36
@kyleboehlen Can you share the Laravel Version of your project (`php artisan --version`)?
And what's the output of `composer why symfony/finder`?

I can't reproduce this error on a fresh Laravel 8 install. That's why I need a bit more information here.

**Comment by kyleboehlen** [comment] 2020-10-27 18:56
@stefanzweifel 
Laravel Framework: 7.28.4
```
barryvdh/laravel-debugbar  v3.5.1   requires  symfony/finder (^4.3|^5)
laravel/framework          v7.28.4  requires  symfony/finder (^5.0)
sebastian/finder-facade    2.0.0    requires  symfony/finder (^4.1|^5.0)
wnx/laravel-stats          v2.4.1   requires  symfony/finder (^4.3 || ^5.0)
```
That being said, it only happens when your config is cached without having published the vendor config for the package.

**Steps to reproduce issue on a fresh laravel installation:**
`composer create-project --prefer-dist laravel/laravel laravelstatstest`
`cd laravelstatstest`
`php artisan config:cache`
`composer require "wnx/laravel-stats" --dev`
`php artisan stats`

**Comment by stefanzweifel** [comment] 2020-10-27 18:57
@kyleboehlen Thanks! Good to know about the config-cache thing. Will have to give this a spin.

**Comment by kyleboehlen** [comment] 2020-10-27 19:01
@stefanzweifel 
I just tested caching the config on a freshly created laravel project without publishing the vendor config and it still resolves the issue. So this really isn't an issue with your package at all, I suppose you could add something in the installation directions of the readme but `config:cache` and `composer dump-autoload` should be the first thing people try when they have an issue like this ¯\\_(ツ)_/¯

**Comment by stefanzweifel** [comment] 2020-10-27 19:04
@kyleboehlen Yeah, will add a note to the README I think. `php artisan config:cache` shouldn't be run on dev machine anyway (IMHO).

As this resolves the original issue mentioned here, I'm gonna close this issue for now.

**Closed by stefanzweifel** 2020-10-27 19:04 UTC
