### ISSUE TITLE
Stats Command fails when run in a project that uses Pest PHP

### ISSUE THREAD

**Issue by domthomas-dev** [stefanzweifel/laravel-stats#218] opened 2023-08-11 10:49 UTC
Hi, probably a problem between two packages ...

```
Message Please run [./vendor/bin/pest] instead.
```

<img width="421" alt="Screenshot 2023-08-11 at 12 45 44" src="https://github.com/stefanzweifel/laravel-stats/assets/17202290/469f11cf-712c-4bc4-8d32-fcdb4e36bdb0">

```
"require": {
        "php": "^8.1",
        "asantibanez/laravel-eloquent-state-machines": "^5.2",
        "blade-ui-kit/blade-heroicons": "^2.0",
        "codenco-dev/codenco-faster": "dev-main",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.0",
        "laravel/horizon": "^5.10",
        "laravel/jetstream": "^2.12",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.7",
        "livewire/livewire": "^2.5",
        "opcodesio/log-viewer": "^1.6",
        "spatie/laravel-activitylog": "^4.5",
        "spatie/laravel-login-link": "^1.1",
        "spatie/laravel-medialibrary": "^10.9",
        "spatie/laravel-ray": "^1.30",
        "spatie/once": "^3.1",
        "spatie/simple-excel": "^3.2.0",
        "wire-elements/pro": "^3.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.7",
        "barryvdh/laravel-ide-helper": "^2.12",
        "codenco-dev/eloquent-model-tester": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "laravel-lang/attributes": "^2.0",
        "laravel-lang/lang": "^12.0",
        "laravel-lang/publisher": "^14.3",
        "laravel/dusk": "^7.6",
        "laravel/pint": "^1.1",
        "laravel/sail": "^1.16",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "nunomaduro/larastan": "^2.0",
        "nunomaduro/phpinsights": "^2.6",
        "pestphp/pest": "^2.0",
        "pestphp/pest-plugin-laravel": "^2.0",
        "spatie/laravel-ignition": "^2.0",
        "wnx/laravel-stats": "^2.11"
    },
```

**Comment by stefanzweifel** [comment] 2023-08-11 11:52
Unfortunately, Pest is currently not supported (see https://github.com/stefanzweifel/laravel-stats/discussions/194).
However, I thought that we added guards that the stats command can still be called, even when Pest installed.

Will do some testing and maybe publish a fix, so that folks can atleast run the `stats`-command in projects using Pest.

**Comment by stefanzweifel** [comment] 2023-08-12 11:54
Official Pest supported is still not there, but I've fixed the issue of running the `stats` command in projects using Pest in #219.

A new version will be released shortly.

**Comment by liamjoc** [comment] 2024-10-01 21:00
@stefanzweifel Unfortunately, I think this issue needs reopening. I'm getting the same error in the console.

pestphp/pest = 3.2.5
pestphp/pest-plugin-laravel = 3.0.0
wnx/laravel-stats = 2.13.2

**Comment by stefanzweifel** [comment] 2024-10-02 06:50
@liamjoc Thanks for the hint. The [composer.json](https://github.com/stefanzweifel/laravel-stats/blob/main/composer.json#L31) currently also doesn't yet use Pest v3. That's something we have to fix.

However reads this: feel free to submit a PR. 
I try to tackle this in the coming days.

**Comment by stefanzweifel** [comment] 2024-10-02 18:26
@liamjoc I'm unable to reproduce this exact issue in a fresh Laravel 11 application. 
However, I run into the same issue when I run `artisan stats` in 1 side project of mine, which uses Pest.

By adding a `var_dump` statement before running `require_once` [here](https://github.com/stefanzweifel/laravel-stats/blob/main/src/ClassesFinder.php#L30) I was able to pint-point the issue to 1 Pest test in my application.

I was able to remove almost all code in that test and still get an issue. In the end the `);` on it's own line was the issue.

This test throws a `InvalidPestCommand`-exception when `artisan stats` scans your app for files.

```php
<?php

it('allows user to register when a valid invite code is provided', function () {
    Notification::assertNotSentTo([$user], VerifyEmail::class
    );
});
```

This test fixes the problem.

```php
<?php

it('allows user to register when a valid invite code is provided', function () {
    Notification::assertNotSentTo([$user], VerifyEmail::class);
});
```

Why does this happen? If have no idea!
The problem can be fixed by updating the test, but finding the faulty test is hard for users.

If someone comes across this issue, I would recommend removing `base_path('tests')` from the `stats.path`-configuration. That way, the `stats`-command won't scan these files.

(I'm closing this issue again)

---

As mentioned/discussed in #194, laravel-stats is not really compatible with Pest. The package looks for classes; this doesn't work with Pest.
I or someone else would have to rebuild the core of the package, to no longer be dependent on classes, but rather determine the type by the file itself.

**Closed by stefanzweifel** 2024-10-02 18:26 UTC
Labels: bug

**Comment by liamjoc** [comment] 2024-10-02 19:14
@stefanzweifel Thank you, I've managed to track down the tests that are causing the problem and it's the same `);` on it's own line. Unfortunately, this is a style across multiple tests.

```php
test('invoke validates with a form request', function () {
    $this->assertActionUsesFormRequest(
        PlanUpdateController::class,
        '__invoke',
        UpdatePlanRequest::class
    );
});
```
