### ISSUE TITLE
TypeError when running stats-command in EventListenerClassifier

### ISSUE THREAD

**Issue by shijie1991** [stefanzweifel/laravel-stats#203] opened 2022-02-22 18:39 UTC
```
 TypeError 

  ReflectionFunction::__construct(): Argument #1 ($function) must be of type Closure|string, array given

  at vendor/wnx/laravel-stats/src/Classifiers/EventListenerClassifier.php:65
     61▕         if (is_string($closure)) {
     62▕             return $closure;
     63▕         }
     64▕ 
  ➜  65▕         $reflection = new ReflectionFunction($closure);
     66▕ 
     67▕         return Arr::get($reflection->getStaticVariables(), 'listener');
     68▕     }
     69▕ 

      +2 vendor frames 
  3   [internal]:0
      Wnx\LaravelStats\Classifiers\EventListenerClassifier::Wnx\LaravelStats\Classifiers\{closure}()

      +2 vendor frames 
  6   [internal]:0
      Wnx\LaravelStats\Classifiers\EventListenerClassifier::Wnx\LaravelStats\Classifiers\{closure}("Illuminate\Database\Events\QueryExecuted")
```

**Comment by stefanzweifel** [comment] 2022-02-22 19:12
@shijie1991 Unfortunately I can't reproduce this error. Could you share a simplifed version of one of your EventListeners that triggers this error?

All I can see from your example is that it's related to `Illuminate\Database\Events\QueryExecuted`.

**Comment by shijie1991** [comment] 2022-02-22 19:22
<img width="677" alt="image" src="https://user-images.githubusercontent.com/11606404/155203374-831103f0-872c-472f-8213-59f9f6ca2f9c.png">


output

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/11606404/155203568-f6d612b2-c617-47a1-bd0f-d6c1aaf9e887.png">


<img width="1167" alt="image" src="https://user-images.githubusercontent.com/11606404/155203639-15ac9f64-e140-4689-b23c-65a794f7da87.png">

**Comment by stefanzweifel** [comment] 2022-02-22 19:31
Sorry, this information doesn't really help me further.
Your application _somehow_ registers something to the EventBus, which `laravel-stats` tries to parse and fails to do so.

Is this an empty Laravel installation?
Or have you registered an [EventListener](https://laravel.com/docs/9.x/events#defining-listeners) or [EventSubscriber](https://laravel.com/docs/9.x/events#writing-event-subscribers) in a weird way?

For example, our test suite registers [this DemoEventListener](https://github.com/stefanzweifel/laravel-stats/blob/main/tests/Stubs/EventListeners/DemoEventListener.php) in the [`EventServiceProvider`](https://github.com/stefanzweifel/laravel-stats/blob/main/tests/Stubs/ServiceProviders/EventServiceProvider.php#L17-L21). 

Do you do the same?

Could you maybe open the `vendor/wnx/laravel-stats/blob/main/src/Classifiers/EventListenerClassifier.php` file in your editor and add an `is_array` condition to the `getEventListener()`-method like below?

```php
    /**
     * @param Closure|string $closure
     * @retrun null|string|object
     * @throws \ReflectionException
     */
    protected function getEventListener($closure)
    {
        if (is_string($closure)) {
            return $closure;
        }

        if (is_array($closure)) {
            dd($closure);
        }

        $reflection = new ReflectionFunction($closure);

        return Arr::get($reflection->getStaticVariables(), 'listener');
    }
```

This would output, where `stats` breaks.

**Comment by stefanzweifel** [comment] 2022-02-22 19:34
Ok, I get the same error in https://github.com/stefanzweifel/laravel-stats/pull/204.
But still can't reproduce this locally with PHP 8.1 and Laravel 9. 🤔

**Comment by shijie1991** [comment] 2022-02-22 19:36
<img width="601" alt="image" src="https://user-images.githubusercontent.com/11606404/155205763-2248e97f-991d-4c59-be53-6d5731ca950f.png">

output

<img width="932" alt="image" src="https://user-images.githubusercontent.com/11606404/155205824-21cd7c0e-a487-40c8-bc35-1388c51f9161.png">

**Comment by stefanzweifel** [comment] 2022-02-22 19:42
The issue has been fixed in https://github.com/stefanzweifel/laravel-stats/pull/204. A new release has been tagged.
https://github.com/stefanzweifel/laravel-stats/releases/tag/v2.8.1

**Closed by stefanzweifel** 2022-02-22 19:42 UTC
Labels: bug

**Comment by shijie1991** [comment] 2022-02-22 19:44
谢谢你 !!!
